Complete last stage
andrew4herman/Easy-Coffee-Machine pull request #1
Opened 2021-12-12 21:46 UTC by andrew4herman

### **Description**

> But just one action isn’t interesting. Let's improve the program so it can do multiple actions, one after another. The program should repeatedly ask what the user wants to do. If the user types "buy", "fill" or "take", then just do what the program did in the previous step. However, if the user wants to switch off the coffee machine, he should type "exit". Then the program should terminate. Also, when the user types "remaining", the program should output all the resources that the coffee machine has.
> 
> Also, do not forget that you can be out of resources for making coffee. If the coffee machine doesn’t have enough resources to make coffee, the program should output a message that says it can't make a cup of coffee.
> 
> And the last improvement to the program at this step—if the user types "buy" to buy a cup of coffee and then changes his mind, he should be able to type "back" to return into the main cycle.

### **Remember, that:**

- For the espresso, the coffee machine needs 250 ml of water and 16 g of coffee beans. It costs $4.
- For the latte, the coffee machine needs 350 ml of water, 75 ml of milk, and 20 g of coffee beans. It costs $7.
- And for the cappuccino, the coffee machine needs 200 ml of water, 100 ml of milk, and 12 g of coffee. It costs $6.

### **Instruction**

> Write a program that will work endlessly to make coffee for all interested persons until the shutdown signal is given.

### **Example**

> Your coffee machine should have the same initial resources as in the example (400 ml of water, 540 ml of milk, 120 g of coffee beans, 9 disposable cups, $550 in cash).
> The symbol > represents the user input. Note that it's not part of the input.

```
Write action (buy, fill, take, remaining, exit): 
> remaining

The coffee machine has:
400 ml of water
540 ml of milk
120 g of coffee beans
9 disposable cups
$550 of money

Write action (buy, fill, take, remaining, exit): 
> buy

What do you want to buy? 1 - espresso, 2 - latte, 3 - cappuccino, back - to main menu: 
> 2
I have enough resources, making you a coffee!

Write action (buy, fill, take, remaining, exit): 
> remaining

The coffee machine has:
50 ml of water
465 ml of milk
100 g of coffee beans
8 disposable cups
$557 of money

Write action (buy, fill, take, remaining, exit): 
> buy

What do you want to buy? 1 - espresso, 2 - latte, 3 - cappuccino, back - to main menu: 
> 2
Sorry, not enough water!

Write action (buy, fill, take, remaining, exit): 
> fill

Write how many ml of water you want to add: 
> 1000
Write how many ml of milk you want to add: 
> 0
Write how many grams of coffee beans you want to add: 
> 0
Write how many disposable cups of coffee you want to add: 
> 0

Write action (buy, fill, take, remaining, exit): 
> remaining

The coffee machine has:
1050 ml of water
465 ml of milk
100 g of coffee beans
8 disposable cups
$557 of money

Write action (buy, fill, take, remaining, exit): 
> buy

What do you want to buy? 1 - espresso, 2 - latte, 3 - cappuccino, back - to main menu: 
> 2
I have enough resources, making you a coffee!

Write action (buy, fill, take, remaining, exit): 
> remaining

The coffee machine has:
700 ml of water
390 ml of milk
80 g of coffee beans
7 disposable cups
$564 of money

Write action (buy, fill, take, remaining, exit): 
> take

I gave you $564

Write action (buy, fill, take, remaining, exit): 
> remaining

The coffee machine has:
700 ml of water
390 ml of milk
80 g of coffee beans
7 disposable cups
$0 of money

Write action (buy, fill, take, remaining, exit): 
> exit
```

2021-12-21 13:47 UTC, taras-nishchymenko requested changes

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/Coffee.java
> +    Coffee(int water, int milk, int coffeeBeans, int price) {
What does int means for these parameters?

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/Coffee.java
> +    private final int water, milk, coffeeBeans, price;
I would suggest declaring all parameters separately

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/Coffee.java
> +    Coffee(int water, int milk, int coffeeBeans, int price) {
Why do we have int price?

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    public void interact(String userOption) {
Is String a good choice for our API?

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +                case CHOOSING_AN_ACTION -> chooseAction(userOption);
Is CHOOSING_AN_ACTION really a state of machine?

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    private void chooseAction(String action) throws Exception {
Choose action doesn’t represent what this method really does

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    private void chooseAction(String action) throws Exception {
Also please avoid such side-effect methods

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +        if (!error.isEmpty())
Always use brackets in such cases

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +            if (resources.length != 4) throw new Exception();
Brackets

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    private void fill(String ingredients) throws Exception {
Is String a good choice for our API?

2021-12-21 13:47 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +public class CoffeeMachine {
Do we really need Throws clause for almost all our methods?

2021-12-21 20:19 UTC, andrew4herman commented on src/machine/Coffee.java
> +    private final int water, milk, coffeeBeans, price;
Done

2021-12-21 20:23 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +        if (!error.isEmpty())
Okay, I'll remember that.
Added.

2021-12-21 20:23 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +            if (resources.length != 4) throw new Exception();
Added

2021-12-21 20:30 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +                case CHOOSING_AN_ACTION -> chooseAction(userOption);
I guess so, at least that is clearly defined in the task description

> The right solution to this problem is to store the current state of the machine. The coffee machine has several states it can be in. For example, the state could be "choosing an action" or "choosing a variant of coffee".

Should I rename it to WAITING_FOR_ACTION or something like that?
I'll be glad to hear your suggestions

2021-12-21 20:42 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +    private void fill(String ingredients) throws Exception {
Replaced that with array of int. Now we are checking if the input is correct before passing it to the fill method, so Throws clause is now unnecessary.

2021-12-21 21:09 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +    public void interact(String userOption) {
That choice was also defined by the task description

> The class should not use system input at all; it only should handle input that comes to it via this method and its string argument.

Also I think that's correct decision, because if the coffee machine don't use system input at all, it cannot guarantee that the input is valid. So it receives raw String which is user option implementation and the checks for validness.
But I also think that there is a much more clearer way to do that, so I'm waiting for your advice.

P.S [task description](https://hyperskill.org/projects/33/stages/180/implement)

2021-12-21 21:23 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +public class CoffeeMachine {
Removed exception throws from every method except one - checkIngredientsFor(), but even that throw is immediately handled when this method is called.

2021-12-21 21:40 UTC, andrew4herman commented on src/machine/Coffee.java
> +    Coffee(int water, int milk, int coffeeBeans, int price) {
> What does int means for these parameters?

Renamed parameters - added "mlOf" and "grOf" prefixes.



> Why do we have int price?

Fixed. Now only the coffeeMachine holds the price of every drink in the priceList field.

2022-01-05 11:48 UTC, taras-nishchymenko requested changes

2022-01-05 11:48 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    public void interact(String userOption) {
In general you as a API designer should decide on right API for you program. In general it’s always good idea to limit your potential users with inly limit number of operations. For example using enum as operation will force your API users to use only defined by you operations, when the String says "you can put everything you want here"

2022-01-05 11:48 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +                if ("back".equals(userOption)) {
I would suggest to extract it into some method

2022-01-05 11:48 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +                int[] resources = Arrays.stream(userOption.split(" "))
I would suggest to extract it into some method

2022-01-05 11:48 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +                    if (coffee.isEmpty()) {
Seems like not right optional usage. Find some useful info here https://www.youtube.com/watch?v=7Iy1hVEXxsU

2022-01-05 11:48 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +            case "1" -> Optional.of(Coffee.ESPRESSO);
Do we really need Optional here? Maybe we can come up with some configuration that will store information about coffee?

2022-01-05 18:36 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +                if ("back".equals(userOption)) {
Extracted

2022-01-05 18:36 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +                int[] resources = Arrays.stream(userOption.split(" "))
Also extracted

2022-01-05 21:14 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +                    if (coffee.isEmpty()) {
Thank you for that resource. Anyway, according to your comment below I have removed Optional usage from that

2022-01-05 21:18 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +            case "1" -> Optional.of(Coffee.ESPRESSO);
Agree with you. Removed Optional, but I don't really get the bit about the configuration. Added NONE constant to Coffee enum, so it represents null and returns when option is incorrect

2022-01-09 14:57 UTC, taras-nishchymenko approved these changes

2022-01-09 14:57 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +    private void chooseCoffeeOp(String userOption) {
What is op?

2022-01-09 14:57 UTC, taras-nishchymenko commented on src/machine/CoffeeMachine.java
> +        );
Why it’s here?

2022-01-09 15:22 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +    private void chooseCoffeeOp(String userOption) {
'op' stands for 'option' like chooseCoffeeOption. Should I rename it to full name or change to something like chooseCoffeeProcess?

2022-01-09 15:37 UTC, andrew4herman commented on src/machine/CoffeeMachine.java
> +        );
Extracted using resources to separate method takeIngredientsFor(). Also replaced adding money part from that method, so makeCoffee() method had only one line of code that outputs a message. I guess it's unnecessary to hold a separate method for that, so removed it at all.

2022-01-10 08:19 UTC, merged